/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Transaction } from './transaction';

export class Approval {
    /**
    * Approval ID
    */
    'id'?: string;
    /**
    * Approval state
    */
    'state'?: Approval.StateEnum;
    /**
    * Approval completion timestamp
    */
    'completedAt'?: Date;
    /**
    * Approval requestor
    */
    'requestor'?: string;
    /**
    * Approval context
    */
    'context'?: string;
    /**
    * Approval creation timestamp
    */
    'createdAt'?: Date;
    /**
    * Approval message
    */
    'message'?: string;
    'tags'?: { [key: string]: string; };
    /**
    * If requesting authorization on a user\'s behalf, provide the email to let the approvers know.
    */
    'onBehalfOf'?: string;
    /**
    * Arbitrary JSON data that gets passed to webhooks
    */
    'payload'?: { [key: string]: any; };
    'transactions'?: Array<Transaction>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "Approval.StateEnum"
        },
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date"
        },
        {
            "name": "requestor",
            "baseName": "requestor",
            "type": "string"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "onBehalfOf",
            "baseName": "onBehalfOf",
            "type": "string"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<Transaction>"
        }    ];

    static getAttributeTypeMap() {
        return Approval.attributeTypeMap;
    }
}

export namespace Approval {
    export enum StateEnum {
        Pending = <any> 'pending',
        Verified = <any> 'verified',
        Denied = <any> 'denied',
        Cancelled = <any> 'cancelled',
        Expired = <any> 'expired'
    }
}
