/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthorizeRequest {
    'message': string;
    'tag': { [key: string]: string; };
    /**
    * If requesting authorization on a user\'s behalf, provide the email to let the approvers know.
    */
    'onBehalfOf'?: string;
    'context'?: string;
    /**
    * Arbitrary JSON data that gets passed to webhooks
    */
    'payload'?: { [key: string]: any; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "onBehalfOf",
            "baseName": "onBehalfOf",
            "type": "string"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "string"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return AuthorizeRequest.attributeTypeMap;
    }
}

