/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OpenID {
    /**
    * OpenID Connect issuer URL
    */
    'issuer'?: string;
    /**
    * OpenID Connect client ID
    */
    'clientID'?: string;
    /**
    * OpenID Connect client secret
    */
    'clientSecret'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "clientID",
            "baseName": "clientID",
            "type": "string"
        },
        {
            "name": "clientSecret",
            "baseName": "clientSecret",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OpenID.attributeTypeMap;
    }
}

