/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Permission } from './permission';

export class PermissionsReply {
    'permissions'?: Array<Permission>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<Permission>"
        }    ];

    static getAttributeTypeMap() {
        return PermissionsReply.attributeTypeMap;
    }
}

