/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Query {
    /**
    * Page number
    */
    'page'?: number;
    /**
    * Items per page
    */
    'perPage'?: number;
    /**
    * Search query
    */
    'q'?: string;
    /**
    * Filter by permission
    */
    'permission'?: string;
    /**
    * Sort field
    */
    'sortBy'?: string;
    /**
    * Sort direction
    */
    'sortDir'?: Query.SortDirEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "perPage",
            "baseName": "perPage",
            "type": "number"
        },
        {
            "name": "q",
            "baseName": "q",
            "type": "string"
        },
        {
            "name": "permission",
            "baseName": "permission",
            "type": "string"
        },
        {
            "name": "sortBy",
            "baseName": "sortBy",
            "type": "string"
        },
        {
            "name": "sortDir",
            "baseName": "sortDir",
            "type": "Query.SortDirEnum"
        }    ];

    static getAttributeTypeMap() {
        return Query.attributeTypeMap;
    }
}

export namespace Query {
    export enum SortDirEnum {
        Asc = <any> 'asc',
        Desc = <any> 'desc'
    }
}
