/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RoutingRule {
    'id'?: string;
    /**
    * Name of tag associated with the routing rule
    */
    'tagName': string;
    /**
    * Tag value that must match for this rule to fire
    */
    'tagValue': string;
    'description'?: string;
    /**
    * The type of target for the routing rule
    */
    'targetType': RoutingRule.TargetTypeEnum;
    /**
    * The ID of the target (approval group or user)
    */
    'targetId': string;
    /**
    * The email of the target
    */
    'targetEmail'?: string;
    /**
    * The name of the target
    */
    'targetName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "tagName",
            "baseName": "tagName",
            "type": "string"
        },
        {
            "name": "tagValue",
            "baseName": "tagValue",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "targetType",
            "baseName": "targetType",
            "type": "RoutingRule.TargetTypeEnum"
        },
        {
            "name": "targetId",
            "baseName": "targetId",
            "type": "string"
        },
        {
            "name": "targetEmail",
            "baseName": "targetEmail",
            "type": "string"
        },
        {
            "name": "targetName",
            "baseName": "targetName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RoutingRule.attributeTypeMap;
    }
}

export namespace RoutingRule {
    export enum TargetTypeEnum {
        ApprovalGroup = <any> 'approval_group',
        User = <any> 'user'
    }
}
