/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectWise } from './connectWise';
import { OpenID } from './openID';

export class Settings {
    /**
    * Organization subdomain
    */
    'subdomain'?: string;
    /**
    * Organization name
    */
    'name'?: string;
    'openID'?: OpenID;
    /**
    * SCIM API secret
    */
    'scimSecret'?: string;
    /**
    * Email notification template
    */
    'emailTemplate'?: string;
    /**
    * SMS notification template
    */
    'smsTemplate'?: string;
    'connectWise'?: ConnectWise;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subdomain",
            "baseName": "subdomain",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "openID",
            "baseName": "openID",
            "type": "OpenID"
        },
        {
            "name": "scimSecret",
            "baseName": "scimSecret",
            "type": "string"
        },
        {
            "name": "emailTemplate",
            "baseName": "emailTemplate",
            "type": "string"
        },
        {
            "name": "smsTemplate",
            "baseName": "smsTemplate",
            "type": "string"
        },
        {
            "name": "connectWise",
            "baseName": "connectWise",
            "type": "ConnectWise"
        }    ];

    static getAttributeTypeMap() {
        return Settings.attributeTypeMap;
    }
}

