/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Transaction {
    /**
    * Transaction identifier
    */
    'id'?: string;
    /**
    * Subject user ID
    */
    'subject'?: string;
    /**
    * Subject user name
    */
    'subjectName'?: string;
    /**
    * Transaction state
    */
    'state'?: Transaction.StateEnum;
    /**
    * Transaction completion timestamp
    */
    'completedAt'?: Date;
    /**
    * Transaction requestor
    */
    'requestor'?: string;
    /**
    * Transaction context
    */
    'context'?: string;
    /**
    * Transaction creation timestamp
    */
    'createdAt'?: Date;
    /**
    * Transaction expiration timestamp
    */
    'expiresAt'?: Date;
    /**
    * Transaction message
    */
    'message'?: string;
    /**
    * User-provided message
    */
    'userMessage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "subjectName",
            "baseName": "subjectName",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "Transaction.StateEnum"
        },
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date"
        },
        {
            "name": "requestor",
            "baseName": "requestor",
            "type": "string"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "userMessage",
            "baseName": "userMessage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }
}

export namespace Transaction {
    export enum StateEnum {
        Pending = <any> 'pending',
        Verified = <any> 'verified',
        Denied = <any> 'denied',
        Cancelled = <any> 'cancelled',
        Expired = <any> 'expired'
    }
}
