/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Company } from './company';

export class User {
    /**
    * Unique user identifier
    */
    'id'?: string;
    /**
    * User role
    */
    'role'?: User.RoleEnum;
    /**
    * Display username
    */
    'username'?: string;
    /**
    * User first name
    */
    'firstName': string;
    /**
    * User last name
    */
    'lastName': string;
    /**
    * User email address
    */
    'email'?: string;
    /**
    * User phone number
    */
    'phone'?: string;
    'company'?: Company;
    /**
    * User direct permissions
    */
    'permissions'?: Array<string>;
    /**
    * Permissions from groups
    */
    'groupPermissions'?: Array<string>;
    /**
    * Permission group IDs
    */
    'permissionGroups'?: Array<string>;
    /**
    * User messaging preference
    */
    'messagingPreference'?: User.MessagingPreferenceEnum;
    /**
    * Whether user has passkeys configured
    */
    'hasPasskeys'?: boolean;
    /**
    * User creation timestamp
    */
    'createdAt'?: Date;
    /**
    * Last authentication timestamp
    */
    'lastAuthenticated'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "User.RoleEnum"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "Company"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>"
        },
        {
            "name": "groupPermissions",
            "baseName": "groupPermissions",
            "type": "Array<string>"
        },
        {
            "name": "permissionGroups",
            "baseName": "permissionGroups",
            "type": "Array<string>"
        },
        {
            "name": "messagingPreference",
            "baseName": "messagingPreference",
            "type": "User.MessagingPreferenceEnum"
        },
        {
            "name": "hasPasskeys",
            "baseName": "hasPasskeys",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "lastAuthenticated",
            "baseName": "lastAuthenticated",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

export namespace User {
    export enum RoleEnum {
        Admin = <any> 'admin',
        User = <any> 'user',
        SuperAdmin = <any> 'super_admin'
    }
    export enum MessagingPreferenceEnum {
        Email = <any> 'email',
        Sms = <any> 'sms',
        Both = <any> 'both'
    }
}
