/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WebhookEvents {
    /**
    * When true, transaction verifications will invoke the webhook
    */
    'verify'?: boolean;
    /**
    * When true, transaction denials will invoke the webhook
    */
    'deny'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "verify",
            "baseName": "verify",
            "type": "boolean"
        },
        {
            "name": "deny",
            "baseName": "deny",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return WebhookEvents.attributeTypeMap;
    }
}

