/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WebhookEvents } from './webhookEvents';

/**
* A webhook configuration object
*/
export class Webhook {
    /**
    * The unique identifier of the webhook
    */
    'id': string;
    /**
    * The URL where webhook events will be sent
    */
    'url': string;
    /**
    * Optional secret used to sign webhook payloads (HMAC-SHA256)
    */
    'secret'?: string;
    /**
    * Optional approval group ID to associate with the webhook
    */
    'authGroupID'?: string;
    'events': WebhookEvents;
    /**
    * When the webhook was created
    */
    'createdAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "authGroupID",
            "baseName": "authGroupID",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "WebhookEvents"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Webhook.attributeTypeMap;
    }
}

