/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WebhookEvents } from './webhookEvents';

/**
* Input schema for creating or updating a webhook
*/
export class WebhookInput {
    'url': string;
    /**
    * Optional secret used to sign webhook payloads (HMAC-SHA256). If a secret is already set, omitting this will preserve the existing secret.
    */
    'secret'?: string;
    /**
    * Optional approval group ID to associate with the webhook
    */
    'authGroupID'?: string;
    'events': WebhookEvents;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "authGroupID",
            "baseName": "authGroupID",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "WebhookEvents"
        }    ];

    static getAttributeTypeMap() {
        return WebhookInput.attributeTypeMap;
    }
}

