/**
 * SendAuth API
 * Authentication and identity management API for SendAuth platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WebTX {
    /**
    * Transaction message
    */
    'message'?: string;
    /**
    * ConnectWise reference
    */
    'connectwise'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "connectwise",
            "baseName": "connectwise",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WebTX.attributeTypeMap;
    }
}

